apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: web-app
spec:
  selector:
    type: hello-demo
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 8080
    # nodePort: 30001
